apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  containers:
  - name: container-name
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-name
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-name
          key: password