apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  volumes:
  - name: volume-name
    emptyDir: {}
  containers:
  # Container 1
  - name: ubuntu1
    image: ubuntu
    volumeMounts:
    - name: volume-name
      mountPath: /ubuntu1
    # command: ["sleep 3000"]
    command:
    - sleep
    - "3000"
  # Container 2
  - name: ubuntu2
    image: ubuntu
    volumeMounts:
    - name: volume-name
      mountPath: ubuntu2
    # command: ["sleep 3000"]
    command:
    - sleep
    - "3000"
