apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  volumes:
  - name: volume-name
    # Default --> emptyDir: {}
  containers:
  - name: container-name
    image: redis
    # ports:
    # - containerPort: 80
    volumeMounts:
    - name: volume-name
      mountPath: /data/redis
