apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: podname
      labels:
        app: web
    spec:
      containers:
        - name: containername
          image: nginx:latest
          ports:
          - containerPort: 80