apiVersion: v1
kind: Pod
metadata:
  name: pod-name
spec:
  volumes:
    # $$$$$$$$$$$$
  - name: pvc-pod-nginx
    persistentVolumeClaim:
      claimName: pvc 
      # ************
  containers:
  - name: container-name
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc-pod-nginx
      # $$$$$$$$$$$$
      mountPath: /usr/share/nginx/html

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # ************
  name: pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi